// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs1OSQ0iDUNtY7FmsZHSLCyyEVCOKW_U',
    appId: '1:71228039114:web:0cf0e2d594d77c0e0ff933',
    messagingSenderId: '71228039114',
    projectId: 'minded-6bebe',
    authDomain: 'minded-6bebe.firebaseapp.com',
    storageBucket: 'minded-6bebe.appspot.com',
    measurementId: 'G-E8WFX8M3H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUGwFiFTorf7KKpuvRaSN38A_5t2ScmY',
    appId: '1:71228039114:android:6dac43c1ee77b71e0ff933',
    messagingSenderId: '71228039114',
    projectId: 'minded-6bebe',
    storageBucket: 'minded-6bebe.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBstUMBvqvA0A3pNf50pDnyFV-OoyLW_e4',
    appId: '1:71228039114:ios:df03a6c32d116c040ff933',
    messagingSenderId: '71228039114',
    projectId: 'minded-6bebe',
    storageBucket: 'minded-6bebe.appspot.com',
    iosClientId: '71228039114-04eq21p707216tjnhlbnru6olfok82cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.mindedHub.RunnerTests',
  );
}
